### ISSUE TITLE
No longer supports Sublime Text 3

### ISSUE THREAD

**Issue by OKNoah** [rossedman/derby#7]
It looks like Sublime Text 3 no longer works with Derby.

I've tried searching for it in Package Control, and cloning the repo, but no joy.

**Comment by rossedman** [comment]
@OKNoah Hey, I have marked this project as abandon. May return to it as it needs a serious update. I will look into this and possibly release a new version but currently don't have time. Thanks

**Comment by bikeatefoucault** [comment]
Just getting into bourbon...would love to see this.

**Comment by OKNoah** [comment]
Looks like the project is back? May get back into Bourbon, then :)

**Comment by rossedman** [comment]
@OKNoah It is. Would love to get any feedback you have. The documents portion has been removed and the focus is just on autocompletions. I have been using Bourbon a lot again and forgot how much I liked SASS.
